import time

#based on the book The Most Dangerous Game
print (" You wake up on an island full of trees, your mind is in a daze.")
print (" You try to remember your own name... ")
name = input("What was it again? ") 
print ("Now I remember it was" , name)
time.sleep(1.5)
print ("You walk around the island and find a man with a rugged face and a few scars on his face.")
time.sleep(3)
print ("He introduces himself as General Health and he explains that he is the owner of this island.")
time.sleep(3)
print ("You ask him what he means when he says that 'he owns this island.'")
time.sleep(2.5)
print ("General Health starts to explain his back story...")
time.sleep(2)


print (' "You see I am an experienced hunter, as are you , and quite frankly I have started to find hunting boring." ')
time.sleep(4.5)
print (' "I have hunted around the world, large rhinos? No problem. Siberian Tigers? Easy. Animals, as you see only have their instinct and strength to win a fight, they do not have the wit to fight against man."')
time.sleep(6)
print (' "This is when I decided to find a new animal, one that is cunning, smart, strong, then it hit me the perfect animal to hunt." ')
time.sleep(5.5)


print ('You have an idea of what he is going to say but you ask anyways, "What do you mean the perfect animal?" ')
time.sleep(4)
print (' "Well my dear', name , 'I am obviously talking about hunting humans." ' )
time.sleep(2.5)
print (' "You see I have done my research on you. You are a very skilled hunter and that is why I brought you to this island. We will both hunt each other!" ' )
time.sleep(5)
print (' The moment you hear this your eyes widen and you immedietly exclaim "You must be out of your mind to be doing this! Are you not afraid of death?! " ')
time.sleep(4)
print ('General Health laughs in your face "Well thats the thrill of the hunt my friend!" ')
time.sleep(3)
print ('You try to leave but the general says to your back "If you win you can keep this island or go home." Seeing no way else to leave the island except killing the general you have to accept his challenge. ')
time.sleep(6)
print ('You tell him that you accept his challenge.')
time.sleep(3)
print (' The general shows a wide smile "Great! Now let me explain the rules."')
time.sleep(3)
print ('"I will supply you with a knife, hunting clothes, and a small amount of food."')
time.sleep(4)
print ('"However, I myself have a Colt Python gun and two hunting dogs by my side. I will alot you a couple of hours as a headstart. Remeber you goal is to kill me." ')
time.sleep(5)
print ('The general throws the supplies at your feet and you start picking them up and you put them on.')
time.sleep(4.5)
print ('" and ......"')
time.sleep(1.3)
print ('"START! " ')
#Not mentioned to player but it takes 3 hits to kill general 
